const LOCATION_LABELS = [
  ["Long Island City", "长岛市"],
  ["Lower Manhattan", "下城 / 金融区"],
  ["Upper East Side", "上东区"],
  ["Upper West Side", "上西区"],
  ["Lower East Side", "下东区"],
  ["Downtown Brooklyn", "布鲁克林市中心"],
  ["Brooklyn Heights", "布鲁克林高地"],
  ["Brighton Beach", "布莱顿海滩"],
  ["8th Avenue", "八大道"],
  ["Cayuga Heights", "卡尤加高地"],
  ["Saratoga Springs", "萨拉托加泉"],
  ["Nassau County", "拿骚县"],
  ["Suffolk County", "萨福克县"],
  ["New York City", "纽约市"],
  ["North York", "北约克"],
  ["Jersey City", "泽西市"],
  ["Midtown", "中城"],
  ["Chelsea", "切尔西"],
  ["Chinatown", "唐人街 / 华埠"],
  ["Two Bridges", "双桥"],
  ["Harlem", "哈莱姆"],
  ["Bensonhurst", "本森赫斯特"],
  ["Homecrest", "霍姆克雷斯特"],
  ["Sheepshead Bay", "羊头湾"],
  ["Gravesend", "格雷夫森德"],
  ["Bath Beach", "巴斯海滩"],
  ["Dyker Heights", "戴克高地"],
  ["Midwood", "中木区"],
  ["Williamsburg", "威廉斯堡"],
  ["Greenpoint", "绿点"],
  ["Bushwick", "布什维克"],
  ["Park Slope", "公园坡"],
  ["Forest Hills", "森林小丘"],
  ["Sunset Park", "日落公园"],
  ["Maspeth", "马斯佩斯"],
  ["Fresh Meadows", "新鲜草原"],
  ["Jackson Heights", "杰克逊高地"],
  ["Elmhurst", "艾姆赫斯特"],
  ["Rego Park", "雷哥公园"],
  ["Astoria", "阿斯托里亚"],
  ["Willowdale", "柳树谷"],
  ["Upstate New York", "纽约上州"],
  ["Staten Island", "史泰登岛"],
  ["Manhattan", "曼哈顿"],
  ["Brooklyn", "布鲁克林"],
  ["Queens", "皇后区"],
  ["The Bronx", "布朗克斯"],
  ["Bronx", "布朗克斯"],
  ["Long Island", "长岛"],
  ["Flushing", "法拉盛"],
  ["Great Neck", "大颈"],
  ["Jericho", "杰里科"],
  ["Hicksville", "希克斯维尔"],
  ["Plainview", "普莱恩维尤"],
  ["East Meadow", "东草原"],
  ["New Hyde Park", "新海德公园"],
  ["Garden City", "花园城"],
  ["Westbury", "西伯里"],
  ["Mineola", "米尼奥拉"],
  ["Manhasset", "曼哈塞特"],
  ["Huntington", "亨廷顿"],
  ["Stony Brook", "石溪"],
  ["Patchogue", "帕乔格"],
  ["Fordham", "福特汉姆"],
  ["Riverdale", "里弗代尔"],
  ["Kingsbridge", "金斯布里奇"],
  ["Pelham Bay", "佩勒姆湾"],
  ["Throgs Neck", "特罗格斯颈"],
  ["St. George", "圣乔治"],
  ["New Dorp", "新多普"],
  ["Tottenville", "托滕维尔"],
  ["Great Kills", "大基尔斯"],
  ["Stapleton", "斯台普顿"],
  ["Brighton", "布莱顿"],
  ["Bay Ridge", "湾脊"],
  ["Bayside", "貝賽"],
  ["Whitestone", "白石镇"],
  ["College Point", "大学点"],
  ["Woodside", "伍德赛德"],
  ["Murray Hill", "莫瑞丘"],
  ["Syosset", "赛奥塞特"],
  ["Commack", "康马克"],
  ["Albany", "奥尔巴尼"],
  ["Colonie", "科勒尼"],
  ["Buffalo", "水牛城"],
  ["Williamsville", "威廉斯维尔"],
  ["Rochester", "罗切斯特"],
  ["Pittsford", "匹兹福德"],
  ["Syracuse", "锡拉丘兹"],
  ["Ithaca", "伊萨卡"],
  ["Heights", "高地"],
] as const;

const CHINESE_LOCATION_ALIASES = [
  ["海湾岭", "湾脊"],
  ["海灣嶺", "湾脊"],
  ["贝赛", "貝賽"],
  ["贝赛德", "貝賽"],
  ["貝賽德", "貝賽"],
  ["白石", "白石镇"],
  ["白石鎮", "白石镇"],
  ["学院点", "大学点"],
  ["學院點", "大學點"],
  ["木边区", "伍德赛德"],
  ["木邊區", "伍德赛德"],
  ["木边", "伍德赛德"],
  ["木邊", "伍德赛德"],
  ["法拉盛梅里山", "莫瑞丘"],
  ["穆雷山", "莫瑞丘"],
  ["默里山", "莫瑞丘"],
  ["茉莉丘", "莫瑞丘"],
  ["马斯佩思", "马斯佩斯"],
  ["馬斯佩思", "马斯佩斯"],
  ["麦斯佩斯", "马斯佩斯"],
  ["麥斯佩斯", "马斯佩斯"],
  ["福德姆", "福特汉姆"],
  ["河谷区", "里弗代尔"],
  ["河谷區", "里弗代尔"],
  ["河代尔", "里弗代尔"],
  ["河代爾", "里弗代尔"],
  ["西奥塞特", "赛奥塞特"],
  ["西奧塞特", "赛奥塞特"],
  ["赛奥塞", "赛奥塞特"],
  ["賽奧塞", "赛奥塞特"],
  ["赛奥西特", "赛奥塞特"],
  ["賽奧西特", "赛奥塞特"],
  ["科马克", "康马克"],
  ["科馬克", "康马克"],
  ["帕奇奥格", "帕乔格"],
  ["帕奇奧格", "帕乔格"],
] as const;

function escapeRegExp(value: string) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

export function toChineseLocationLabel(value: string) {
  const translated = [...LOCATION_LABELS].sort((left, right) => right[0].length - left[0].length).reduce(
    (label, [english, chinese]) => label.replace(new RegExp(escapeRegExp(english), "gi"), chinese),
    value,
  );
  return CHINESE_LOCATION_ALIASES.reduce(
    (label, [legacy, canonical]) => label.replace(new RegExp(`${escapeRegExp(legacy)}(?![\\p{L}\\p{N}])`, "gu"), canonical),
    translated,
  );
}
